### ISSUE TITLE
Sitecore 9.0 u2: A potentially dangerous Request.Form value was detected from the client

### ISSUE THREAD

**Issue by schwindelig** [VGBenjamin/UniversalDebugger#1]
While you have `ValidateRequest="false"`, this will not cover all cases. Since Sitecore 9.0 (u2) ships with `requestValidationMode="4.0"` in the `web.config`, the post back will fail with the following exception:

> A potentially dangerous Request.Form value was detected from the client

One workaround is to set `requestValidationMode` to `2.0` in the web.config. However, this will trigger a recycle of the app pool.

**Comment by VGBenjamin** [comment]
Hello,

Thank you for your comment. I have already had this issue on other projects and I don't think that it is possible to change the code to bypass this issue. If you have a better solution than the web.config modification tell me and I will try to change it!
If not I will add your remark in the readme to help the future users!

**Comment by retohugi** [comment]
Since you're using `Request.Unvalidated.Form` which is a [.Net 4.5 feature](https://docs.microsoft.com/en-us/dotnet/api/system.web.httprequest.unvalidated?view=netframework-4.5) to get the form value, I'd recommend adding to the README, that `requestValidationMode="4.5"` is a requirement for the UniversalDebugger.

BTW: even for the Sitecore 9.1 prerelease the `requestValidationMode` is set to `4.0`.

**Comment by VGBenjamin** [comment]
Ok I have added this to the documentation!
Thank you for your contribution.
